apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: e2e-secret-lodestar
    namespace: openshift-gitops
    envs:
      - .env
configmapGenerator:
  - name: dispatcher-variables-ls
    namespace: openshift-gitops
    envs:
    - .env
